---
sudo: false
language: java
jdk:
- oraclejdk7
- oraclejdk8
env:
- TERM=dumb
install:
- "./gradlew --version"
- mvn --version
script:
- "./gradlew --continue"
- mvn -f bnd-maven-plugin --batch-mode --quiet -Dmaven.repo.local=bnd-maven-plugin/target/m2
  -Dfile=../dist/bundles/biz.aQute.bndlib/biz.aQute.bndlib-latest.jar install:install-file
  install
